#pragma once

#define PROJECTION_UNIFORM_IDX 0
#define LINE_UNIFORM_IDX 1
#define BASE_FACTIONS_UNIFORM_IDX 2
#define HEALTHS_UNIFORM_IDX 2
#define HEALTH_FACTIONS_UNIFORM_IDX 3
#define FLEET_SIZE_UNIFORM_IDX 2

#define SHAPE_PIPELINE_IDX 0
#define SHAPE_BUFF_IDX 0
#define LINE_PIPELINE_IDX 1
#define LINE_BUFF_IDX 1
#define EDGE_PIPELINE_IDX 2
#define EDGE_BUFF_IDX 2
#define UNIT_PIPELINE_IDX 3
#define UNIT_BUFF_IDX 3
#define HEALTH_PIPELINE_IDX 4
#define HEALTH_BUFF_IDX 4
